name: SonarQube Scan

on:
  push:
    branches: [ main, master ]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # ---------------------------
      # Python Setup
      # ---------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # ---------------------------
      # Run Tests + Coverage
      # ---------------------------
      - name: Run tests
        run: |
          pytest tests/ --cov=. --cov-report=xml

      # ---------------------------
      # Verify coverage
      # ---------------------------
      - name: Check coverage file
        run: |
          ls -l coverage.xml

      # ---------------------------
      # Sonar Scan
      # ---------------------------
      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_HOST_URL: http://54.162.248.144:9000
        with:
          args: >
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}
            -Dsonar.sources=.
            -Dsonar.login=squ_4f7ac18302a201ff8063adbbe59d1c2f8bdb4307
            -Dsonar.python.coverage.reportPaths=coverage.xml
